DEFAULT_SETTINGS_PATHS: []
EXCLUDE:
  DIRECTORIES:
  - __pycache__
  - .applydir
  - .cache
  - .eggs
  - .git
  - .idea
  - .mypy_cache
  - .pdm-build
  - .prepdir
  - .pytest_cache
  - .ruff_cache
  - .tox
  - .venv
  - .vibedir
  - '*.egg-info'
  - build
  - dist
  - node_modules
  - venv
  FILES:
  - .gitignore
  - .prepdir/config.yaml
  - ~/.prepdir/config.yaml
  - LICENSE
  - .DS_Store
  - Thumbs.db
  - .env
  - .env.production
  - .coverage
  - coverage.xml
  - .pdm-python
  - pdm.lock
  - '*.pyc'
  - '*.pyo'
  - '*.log'
  - '*.bak'
  - '*.swp'
  - '**/*.log'
REPLACEMENT_UUID: 00000000-0000-0000-0000-000000000000
SCRUB_HYPHENLESS_UUIDS: false
SCRUB_HYPHENATED_UUIDS: false
